package instance_storage

// Instance storage logging constants
const (
	STORED_INSTANCE                = "STORED_INSTANCE"
	STORED_NEW_INSTANCE            = "STORED_NEW_INSTANCE"
	FOUND_DUPLICATE_INSTANCE       = "FOUND_DUPLICATE_INSTANCE"
	DUPLICATE_INSTANCE             = "DUPLICATE_INSTANCE"
	DUPLICATE_RAW_PGCR             = "DUPLICATE_RAW_PGCR"
	FAILED_TO_STORE_INSTANCE       = "FAILED_TO_STORE_INSTANCE"
	FAILED_TO_INITIATE_TRANSACTION = "FAILED_TO_INITIATE_TRANSACTION"
	ERROR_STORING_RAW_PGCR         = "ERROR_STORING_RAW_PGCR"
	ERROR_STORING_INSTANCE_DATA    = "ERROR_STORING_INSTANCE_DATA"
	FAILED_TO_STORE_TO_CLICKHOUSE  = "FAILED_TO_STORE_TO_CLICKHOUSE"
	FAILED_TO_COMMIT_TRANSACTION   = "FAILED_TO_COMMIT_TRANSACTION"
)
