server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Scrape Docker container logs via Docker service discovery
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels:
          ["__meta_docker_container_label_com_docker_compose_service"]
        target_label: "source"
      # - source_labels: ["__meta_docker_container_name"]
      #   regex: "/(.*)"
      #   target_label: "container"
      # - source_labels:
      #     ["__meta_docker_container_label_com_docker_compose_project"]
      #   target_label: "project"
    pipeline_stages:
      - regex:
          # Match log format: [LEVEL][LOGGER] -- EVENT >> key=value key2=value2
          # Timestamp is handled automatically by Loki/Promtail from Docker logs
          expression: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3} \[(?P<level>\w+)\]\[(?P<logger>[^\]]+)\] -- (?P<event>\S+)(?: >>\s*(?P<kv>.*))?$'
      - template:
          source: level
          template: "{{ ToLower .level }}"
      - labels:
          level:
          logger:
          event:
      - logfmt:
          mapping:
            kv: .

  # Optional: scrape host-mapped log files (e.g., ClickHouse logs under volumes/logs)
  # - job_name: host_logs
  #   static_configs:
  #     - targets: [localhost]
  #       labels:
  #         job: host_logs
  #         __path__: /host/logs/**/*
