auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

limits_config:
  retention_period: 30d
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  max_query_series: 500000
  max_cache_freshness_per_query: 10m
  max_query_parallelism: 32
  max_query_length: 721h
  max_query_lookback: 0s
  query_timeout: 5m
  split_queries_by_interval: 15m

frontend:
  max_outstanding_per_tenant: 4096

query_scheduler:
  max_outstanding_requests_per_tenant: 10000

querier:
  query_timeout: 5m

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s
  max_transfer_retries: 0

chunk_store_config:
  max_look_back_period: 0s

compactor:
  working_directory: /loki/compactor
  compactor_ring:
    kvstore:
      store: inmemory
