-- Auto-generated from .env
-- DO NOT EDIT THIS FILE - It will be overwritten by generate-configs.sh

-- Create user
CREATE USER username WITH PASSWORD 'password';

-- Create database
CREATE DATABASE raidhub;

-- Grant permissions
GRANT ALL PRIVILEGES ON DATABASE raidhub TO username;

-- Grant schema usage
\c raidhub
GRANT ALL PRIVILEGES ON SCHEMA public TO username;
